### ISSUE TITLE
Error: sendSOAPActionRequest Error!

### ISSUE THREAD

**Issue by cracker0dks** [NicolaiSchmid/tr064#1]
I get this error if I want to get all Wlan Devs:
`Error: sendSOAPActionRequest Error! [GetGenericAssociatedDeviceInfo] [urn:dslforum-org:service:WLANConfiguration:2] [500]
    at Request._callback (D:\Code\karteDesRumtreibers\node_modules\tr-064\lib\Service.js:352:32)
    at Request.self.callback (D:\Code\karteDesRumtreibers\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (D:\Code\karteDesRumtreibers\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (D:\Code\karteDesRumtreibers\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

My Code: 
```
device.startEncryptedCommunication(function (err, sslDev) {
    var wlan2 = sslDev.services["urn:dslforum-org:service:WLANConfiguration:2"]; //5 ghz
    wlan2.actions.GetGenericAssociatedDeviceInfo({ "NewAssociatedDeviceIndex": 0 }, function (err, result) {
        //A wild error occurs!
    })
})
```

Some notes:
1. I only get this error if a wlan device is online
2. My exact same code works if I use the old lib (before the fork)
3. Not related to this error...: Could it be, that line 260 at https://github.com/NicolaiSchmid/tr064/blob/master/src/Service.js should be: `if (self.logAttempts[i].service == serviceType)` (with two = )

greetings

**Comment by NicolaiSchmid** [comment]
Right now I don't have the time to debug, but I will at the and of the week, please be patient!

**Comment by NicolaiSchmid** [comment]
https://github.com/NicolaiSchmid/tr064/blob/master/src/Service.js#L260 is definetly a bug. I'll fix it. 

But even without a fix, I don't get any errors. Is your FritzBox user and password protected?
Mine is, so I have to call:
`sslDev.login(['nicolai'], ['******']);`

Otherwhise would you please post a copy of the error.

**Comment by cracker0dks** [comment]
This is the error: 
`Error: sendSOAPActionRequest Error! [GetGenericAssociatedDeviceInfo] [urn:dslforum-org:service:WLANConfiguration:2] [500] at Request._callback (D:\Code\karteDesRumtreibers\node_modules\tr-064\lib\Service.js:352:32) at Request.self.callback (D:\Code\karteDesRumtreibers\node_modules\request\request.js:185:22) at Request.emit (events.js:182:13) at Request.<anonymous> (D:\Code\karteDesRumtreibers\node_modules\request\request.js:1161:10) at Request.emit (events.js:182:13) at IncomingMessage.<anonymous> (D:\Code\karteDesRumtreibers\node_modules\request\request.js:1083:12) at Object.onceWrapper (events.js:273:13) at IncomingMessage.emit (events.js:187:15) at endReadableNT (_stream_readable.js:1085:12) at process._tickCallback (internal/process/next_tick.js:63:19)`

I also copy+pasted it above :)
My Fritzbox 5690 is running with password protection at the latest fritz!OS 7
I will test some more later and report if I get anything new.

**Comment by NicolaiSchmid** [comment]
Okay, so I made a mistake in my setup! I'm getting the same error! I'll debug further

**Comment by cracker0dks** [comment]
Solved it, replace https://github.com/NicolaiSchmid/tr064/blob/master/src/Service.js#L206
   
```
  for (var i in vars) {
    body += "<" + vars[i].name + ">";
    body += vars[i].value;
    body += "</" + vars[i].name + ">";
  }
```

With the old code:

```
 var keys = Object.keys(vars);
 keys.forEach(function (key) {
      body += "<" + key + ">";
      body += vars[key];
      body += "</" + key + ">";
 });
```
greetings

**Comment by NicolaiSchmid** [comment]
Did it really? I fixed in my codebase and the error still occurs

**Comment by cracker0dks** [comment]
Yes, no problems... (Even with the latest code, just the  change from above)
This is my code:
```
var tr = require("./tr-064");

getWlanDevsFromDevice({ 
    ip : "192.168.0.1", //Change to router ip
    user : "user", 
    password : "password",
    twoGhz : true,
    fiveGhz : true,
    guest : false,
    }, 
    function (allDevs) {
        console.log(allDevs); //Console logs all active wlan devices
    }
);

function getWlanDevsFromDevice(settings, doneCallback) { //Returns all Wlan Devices from a Fitzbox 
    var tr064 = new tr.TR064();
    var ip = settings["ip"];
    var user = settings["user"];
    var password = settings["password"];
    var twoGhz = settings["twoGhz"];
    var fiveGhz = settings["fiveGhz"];
    var guest = settings["guest"];
       
    tr064.initTR064Device(ip, 49000, function (err, device) {
        var retCnt = 0;
        if (!err) {
            var allDevs = [];
            device.startEncryptedCommunication(function (err, sslDev) {
                if (!err) {
                    sslDev.login([user], [password]);
                    
                    setInterval(function () {
                        var wlan1 = sslDev.services["urn:dslforum-org:service:WLANConfiguration:1"]; //2.4ghz
                        
                        if(twoGhz) {
                            retCnt++;
                            getWlanDevsFromAdapter(wlan1, "2.4ghz", function (devs) {
                                allDevs = allDevs.concat(devs);
                                checkCallback();
                            })
                        }
                    
                        if(fiveGhz) {
                            var wlan2 = sslDev.services["urn:dslforum-org:service:WLANConfiguration:2"]; //5 ghz
                            retCnt++;
                            getWlanDevsFromAdapter(wlan2, "5ghz", function (devs) {
                                allDevs = allDevs.concat(devs);
                                checkCallback();
                            })
                        }

                        if(guest) {
                            var wlan3 = sslDev.services["urn:dslforum-org:service:WLANConfiguration:3"]; //GuestWlan
                            retCnt++;
                            getWlanDevsFromAdapter(wlan3, "GuestWlan", function (devs) {
                                allDevs = allDevs.concat(devs);
                                checkCallback();
                            })
                        }
                    }, 2000)

                } else {
                    console.log("error", err);
                    checkCallback();
                }
            });
        } else {
            console.log("error", err);
        }

        function checkCallback() {
            retCnt--;
            if (retCnt <= 0) {
                //device.stopEncryptedCommunication();
                doneCallback(allDevs);
                allDevs = [];
            }
        }
    });
}

function getWlanDevsFromAdapter(adp, ident, doneCallback) {
    adp.actions.GetTotalAssociations(function (err, result) {
        if(err) {
            console.log(err)
            return  doneCallback(devs);
        }
        var deviceCnt = result["NewTotalAssociations"];
        var cbCnt = 0;
        var devs = [];
        if (deviceCnt == 0) {
            return doneCallback(devs);
        }
        for (var i = 0; i < deviceCnt; i++) {
            adp.actions.GetGenericAssociatedDeviceInfo({ "NewAssociatedDeviceIndex": i }, function (err, result) {
                cbCnt++;
                if(err) {
                    console.log(err)
                    if (cbCnt == deviceCnt) {
                        doneCallback(devs);
                    }
                    return;
                }
                result["WlanIdent"] = ident;
                devs.push(result);
                if (cbCnt == deviceCnt) {
                    doneCallback(devs);
                }
            })
        }
    });
}
```

**Comment by NicolaiSchmid** [comment]
I've published a "fixed" version under the next tag. Could you install '@nicolaischmid/tr064@next' and test?

**Comment by cracker0dks** [comment]
don't see a "next" tag, but I tested with your latest changes and it works.

**Comment by NicolaiSchmid** [comment]
Great!
